#!/usr/bin/perl

# written by andrewt@cse.unsw.edu.au September 2013
# as a starting point for COMP2041/9041 assignment 
# http://cgi.cse.unsw.edu.au/~cs2041/13s2/assignments/perl2python
# edited by hwav057@cse.unsw.edu.au for more functionality September 2013

while ($line = <>) {
	#conditions TO-DO:
	# 1. if loops
	# 2. foreach loops
	# 3. while loops
	# 4. condition handling (perhaps a function that all of the above can call)

	if ($line =~ /^#!/ && $. == 1) {
	
		# translate #! line 
		
		print "#!/usr/bin/python2.7 -u\n";
	} elsif ($line =~ /^\s*#/ || $line =~ /^\s*$/) {
	
		# Blank & comment lines can be passed unchanged
		
		print $line;
	} elsif ($line =~ /^\s*print\s*"(.*)\\n"[\s;]*$/) {
		# Python's print adds a new-line character by default
		# so we need to delete it from the Perl print statement
		#TO-DO: need to consider case of variablie interpolation
		#still not done, can only work when only printing variable
		$temp = $1;
		if ($line =~ /\$/) {
			#case of variable interpolation
			$line = $temp;
			@statement = split / /, $line;
			print "print ";
			foreach $stat (@statement) {
				if ($stat =~ /\$(.+)/) {
					print "$1";
				} else {
					print $stat;
				}
			}
			print "\n";
		} else {
			print "print \"$1\"\n";
		}	
	} elsif ($line =~ /^\s*\$(.+)\;$/) {
		#declaring a variable 
		#python just removes the dollar sign and semi-colon
		($a,$temp) = split /\s*\=\s*/, $1;	
		if ($temp =~ /\$/) {
			#check if each item is a variable and interp
			@temp = split / /, $temp;
			print "$a = ";
			foreach $item (@temp) {
				if ($item =~ /\$/) {
					$item =~ s/\$//;
				}	
				print "$item ";
			}
			print "\n";
		} else {
			print "$a = $temp\n";
		}
 	} elsif ($line =~ /^\sif\s*\((.*)\)\s*\{\s*$/) {
		#if condition
		#NOT COMPLETE
		$condition = $1;
		print "hi and $condition\n";
	} else {
	
		# Lines we can't translate are turned into comments
		
		print "#$line\n";
	}
}
